import type { Metadata } from "next";
import Header from "@/components/layouts/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "ItGeniy121",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Header></Header>
        {children}
        </body>
    </html>
  );
}
